### PR TITLE
fix: Fix extraEnv reference

### PR DESCRIPTION
**Pull request by flamarion**
fix: Fix extraEnv reference

### CODE REVIEW

**Comment by zacharyblasczyk** [comment]
https://github.com/search?q=repo%3Awandb%2Fhelm-charts%20extraEnv&type=code 

@jsbroks, did we intentionally name these differently?

**Review by jsbroks — CHANGES_REQUESTED** [review]
This is a breaking change, we cannot do this

**Comment by flamarion** [comment]
Without this, we can't pass, for example, `HTTP_PROXY` env var to the Operator to pull the definitions and charts.
Is there any alternative?

**Comment by zacharyblasczyk** [comment]
@flamarion, can you update all the refs to `extaEnv`.

**Comment by flamarion** [comment]
Done!  Could you check if this is what you wanted, @zacharyblasczyk ?

**Comment by flamarion** [comment]
@jsbroks  `{{- if .Values.extraEnv }}` was evaluated, but the `{{- toYaml .Values.extraEnvs | nindent 8 }}` never happened, so I don't think this would break stuff.

**Review by danielpanzella — APPROVED** [review]

**Review by jsbroks — APPROVED** [review]

**Pull request merged**
